services:
  db:
    image: postgres:15
    container_name: hbms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hbms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/HBMS_full_deployment.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/HBMS_mock_data.sql:/docker-entrypoint-initdb.d/02_mock.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: hbms_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    command: >
      sh -c "
      sleep 5 &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    image: nginx:alpine
    container_name: hbms_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  pgdata: